// <auto-generated />
namespace VET_CLINIC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _6th : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_6th));
        
        string IMigrationMetadata.Id
        {
            get { return "202303201439508_6th"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
